name: "Documentation"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch || github.ref != 'refs/tags/v*' }}

jobs:
  build-and-deploy:
    name: "Documentation"
    runs-on: [self-hosted, gpu-v100]
    timeout-minutes: 360
    permissions:
      actions: write
      contents: write
      statuses: write
    if: github.event_name == 'push' || !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: "1"
      - name: Set up environment
        shell: julia --color=yes --project=docs {0}
        run: |
          println("--- Instantiating project")
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
        env:
          DATADEPS_ALWAYS_ACCEPT: true
          JULIA_PKG_PRECOMPILE_AUTO: 0
      - name: Building documentation
        run: julia --color=yes --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATADEPS_ALWAYS_ACCEPT: true
          JULIA_DEBUG: "Documenter"
