name: "Format Check"

on:
  push:
    branches:
      - master
    tags: ["*"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  runic:
    name: "Runic"
    uses: "SciML/.github/.github/workflows/runic.yml@v1"
    secrets: "inherit"
